"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { FiBarChart2, FiChevronDown, FiDollarSign, FiFileText, FiHome, FiLogOut, FiMenu, FiSettings, FiUsers, FiX } from "react-icons/fi";
import { createClient } from "@/lib/supabase/client";
const primary = [{ href: "/dashboard", label: "Tableau de bord", icon: FiBarChart2 }, { href: "/biens", label: "Biens", icon: FiHome }, { href: "/locataires", label: "Locataires", icon: FiUsers }, { href: "/contrats", label: "Contrats", icon: FiFileText }, { href: "/loyers", label: "Paiements", icon: FiDollarSign }];
const secondary = [{ href: "/fiscalite", label: "Fiscalité", icon: FiBarChart2 }, { href: "/documents", label: "Documents", icon: FiFileText }, { href: "/parametres", label: "Paramètres", icon: FiSettings }];
export default function Sidebar() { const path = usePathname(); const [open, setOpen] = useState(false), [name, setName] = useState("Yassine A."); useEffect(() => { createClient().auth.getUser().then(({ data }) => { if (data.user) setName(data.user.user_metadata?.full_name ?? data.user.email?.split("@")[0] ?? "Propriétaire"); }); }, []); const signOut = async () => { await createClient().auth.signOut(); location.href = "/login"; }; const nav = (items: typeof primary) => items.map(({ href, label, icon: Icon }) => { const active = href === "/dashboard" ? path === href : (path ?? "").startsWith(href); return <Link key={href} href={href} onClick={() => setOpen(false)} className={`relative flex items-center gap-3 rounded-lg px-4 py-3 text-sm font-medium transition ${active ? "bg-white/10 text-white shadow-[inset_3px_0_0_#10b981]" : "text-[#c5ced9] hover:bg-white/5 hover:text-white"}`}><Icon className="text-lg" />{label}</Link>; }); return <><button onClick={() => setOpen(true)} className="fixed left-3 top-3 z-40 rounded-lg bg-[#0c1b2e] p-3 text-white md:hidden" aria-label="Ouvrir le menu"><FiMenu /></button>{open && <button onClick={() => setOpen(false)} className="fixed inset-0 z-40 bg-black/40 md:hidden" aria-label="Fermer" />}<aside className={`fixed inset-y-0 left-0 z-50 flex w-[252px] shrink-0 flex-col border-r border-[#21334b] bg-[#0c1b2e] transition-transform md:sticky md:top-0 md:h-screen md:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><button onClick={() => setOpen(false)} className="absolute right-3 top-3 p-2 text-white md:hidden"><FiX /></button><div className="px-5 pb-5 pt-6"><Image src="/logo.png" alt="EasyLocation Immo" width={180} height={54} className="h-12 w-auto object-contain object-left" priority /><p className="mt-2 text-xs text-[#8fa1b5]">Location simplifiée, gestion maîtrisée.</p></div><nav className="flex-1 overflow-y-auto px-3 py-3"><div className="space-y-1">{nav(primary)}</div><div className="my-5 h-px bg-[#203148]" /><div className="space-y-1">{nav(secondary)}</div></nav><div className="border-t border-[#21334b] p-4"><button className="mb-3 flex w-full items-center gap-3 px-2 py-2 text-sm text-[#d5dde6]"><FiHome /><span className="flex-1">Agence Marrakech</span><FiChevronDown /></button><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full border border-[#0ba76b] bg-[#102c2a] text-xs font-bold text-[#3dd399]">{name.slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">{name}</p><p className="text-xs text-[#8191a5]">Administrateur</p></div><button onClick={signOut} className="p-2 text-[#8191a5] hover:text-[#ef6a5b]" aria-label="Déconnexion"><FiLogOut /></button></div></div></aside></>; }
