import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function WelcomePage() {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: profile } = user ? await supabase.from("profiles").select("nom, prenom, email").eq("id", user.id).maybeSingle() : { data: null };
  const { data: subscription } = user ? await supabase.from("subscriptions").select("plan, status, end_date").eq("user_id", user.id).in("status", ["active", "trialing"]).order("created_at", { ascending: false }).limit(1).maybeSingle() : { data: null };
  const name = profile?.prenom || profile?.nom || user?.email?.split("@")[0] || "partenaire";
  return <main className="min-h-screen bg-[#07111f] px-6 py-10 text-white"><div className="mx-auto max-w-5xl"><Link href="/" className="text-lg font-bold">Easy Location <span className="text-cyan-300">IMMO</span></Link><section className="mt-14 rounded-3xl border border-cyan-300/20 bg-gradient-to-br from-cyan-400/15 to-blue-500/10 p-8 sm:p-12"><p className="text-xs font-bold uppercase tracking-[.24em] text-cyan-300">Bienvenue dans votre espace</p><h1 className="mt-4 text-4xl font-bold tracking-tight">Bonjour {name} 👋</h1><p className="mt-4 max-w-2xl text-slate-300">Votre accès a été validé. Configurez votre portefeuille immobilier et commencez à piloter votre activité.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/dashboard" className="rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-cyan-300">Accéder au dashboard →</Link><Link href="/biens" className="rounded-xl border border-white/15 px-5 py-3 text-sm font-semibold hover:bg-white/10">Ajouter mon premier bien</Link></div></section><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border border-white/10 bg-white/[.06] p-6"><h2 className="text-xl font-bold">Démarrage en 3 étapes</h2><div className="mt-6 space-y-4"><Step number="1" title="Compléter votre profil" description="Ajoutez vos coordonnées et les informations de votre activité." href="/parametres" /><Step number="2" title="Ajouter un bien" description="Créez votre premier bien avec son loyer et son statut." href="/biens" /><Step number="3" title="Ajouter un locataire" description="Centralisez vos locataires, contrats et paiements." href="/locataires" /></div></section><aside className="rounded-2xl border border-white/10 bg-white/[.06] p-6"><p className="text-xs uppercase tracking-wider text-slate-400">Votre accès</p><h2 className="mt-3 text-2xl font-bold capitalize">Plan {subscription?.plan ?? "Bêta"}</h2><span className="mt-3 inline-block rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-300">{subscription?.status === "trialing" ? "Période d’essai" : subscription?.status === "active" ? "Actif" : "Sur invitation"}</span><p className="mt-5 text-sm leading-6 text-slate-400">Votre espace est prêt. Vous pourrez gérer votre abonnement depuis la page dédiée.</p><Link href="/abonnement" className="mt-5 block text-sm font-semibold text-cyan-300">Voir mon abonnement →</Link></aside></div></div></main>;
}

function Step({ number, title, description, href }: { number: string; title: string; description: string; href: string }) { return <Link href={href} className="flex gap-4 rounded-xl border border-white/10 bg-white/[.04] p-4 transition hover:border-cyan-300/30 hover:bg-cyan-400/[.06]"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-cyan-400 text-sm font-black text-slate-950">{number}</span><span><strong className="block text-sm">{title}</strong><span className="mt-1 block text-xs leading-5 text-slate-400">{description}</span></span><span className="ml-auto text-cyan-300">→</span></Link>; }
