"use client";

import Link from "next/link";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function DevenirPartenairePage() {
  const [form, setForm] = useState({ nom: "", email: "", telephone: "", ville: "", type_profil: "proprietaire", nombre_biens: "1", message: "" });
  const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle");
  const [error, setError] = useState("");
  function update(key: string, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setState("loading"); setError(""); const { error: requestError } = await createClient().from("partner_requests").insert({ ...form, nombre_biens: Number(form.nombre_biens) }); if (requestError) { setError("Impossible d’envoyer votre demande pour le moment."); setState("error"); } else setState("success"); }
  if (state === "success") return <main className="flex min-h-screen items-center justify-center bg-[#07111f] px-6"><div className="max-w-md rounded-3xl border border-cyan-300/20 bg-white/[.07] p-8 text-center text-white"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-400 text-xl font-black text-slate-950">✓</div><h1 className="mt-5 text-2xl font-bold">Demande bien reçue</h1><p className="mt-3 text-sm leading-6 text-slate-300">Notre équipe va examiner votre dossier. Vous recevrez un email après validation par l’administrateur.</p><Link href="/" className="mt-6 inline-block text-sm font-semibold text-cyan-300">Retour à l’accueil</Link></div></main>;
  return <main className="min-h-screen bg-[#07111f] px-6 py-10 text-white"><div className="mx-auto max-w-5xl"><Link href="/" className="text-lg font-bold">Easy Location <span className="text-cyan-300">IMMO</span></Link><div className="mt-12 grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><section><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-300">Devenir partenaire</p><h1 className="mt-4 text-4xl font-bold tracking-tight">Construisons une gestion immobilière plus simple.</h1><p className="mt-5 leading-7 text-slate-300">Présentez-nous votre activité. Après étude, notre équipe vous donnera accès à votre espace professionnel.</p><div className="mt-8 space-y-4 text-sm text-slate-300"><p>✓ Dossier examiné par notre équipe</p><p>✓ Invitation sécurisée après approbation</p><p>✓ Mot de passe créé par vos soins</p></div></section><form onSubmit={submit} className="rounded-3xl border border-white/10 bg-white/[.07] p-6 shadow-2xl shadow-cyan-950/20"><h2 className="text-xl font-bold">Votre demande</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Nom complet"><input required value={form.nom} onChange={(e) => update("nom", e.target.value)} /></Field><Field label="Email professionnel"><input required type="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></Field><Field label="Téléphone"><input required value={form.telephone} onChange={(e) => update("telephone", e.target.value)} /></Field><Field label="Ville"><input required value={form.ville} onChange={(e) => update("ville", e.target.value)} /></Field><Field label="Profil"><select value={form.type_profil} onChange={(e) => update("type_profil", e.target.value)}><option value="proprietaire">Propriétaire</option><option value="agence">Agence immobilière</option><option value="conciergerie">Conciergerie</option><option value="comptable">Expert-comptable</option></select></Field><Field label="Nombre de biens"><input required min="1" type="number" value={form.nombre_biens} onChange={(e) => update("nombre_biens", e.target.value)} /></Field></div><Field label="Votre besoin"><textarea rows={4} value={form.message} onChange={(e) => update("message", e.target.value)} /></Field>{state === "error" && <p className="mt-4 rounded-xl bg-red-400/10 px-3 py-2 text-sm text-red-200">{error}</p>}<button disabled={state === "loading"} className="mt-5 w-full rounded-xl bg-cyan-400 px-4 py-3 text-sm font-bold text-slate-950 transition hover:bg-cyan-300 disabled:opacity-50">{state === "loading" ? "Envoi en cours..." : "Envoyer ma demande"}</button><p className="mt-4 text-center text-[11px] text-slate-500">Vos informations seront utilisées uniquement pour traiter votre demande.</p></form></div></div></main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="flex flex-col gap-1.5 text-xs font-semibold text-slate-300">{label}{<span className="contents">{children}</span>}</label>; }
