"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { FiAlertCircle, FiArrowRight, FiCalendar, FiCheck, FiClock, FiFileText, FiHome, FiPlus, FiRadio, FiSend, FiUser, FiX } from "react-icons/fi";
import { getBiens, Bien } from "@/lib/supabase/biens";
import { getLoyers, Loyer } from "@/lib/supabase/loyers";

type Priority = "Critique" | "Élevée" | "Moyenne" | "Faible";
type ActionItem = { id: string; kind: "late" | "contract" | "payment" | "vacancy" | "document" | "inspection"; title: string; subtitle: string; tenant: string; property: string; address: string; due: string; amount?: number; priority: Priority; cta: string; image: string; urgent?: boolean };

const actions: ActionItem[] = [
  { id: "late", kind: "late", title: "Relancer le locataire en retard", subtitle: "Paiement du loyer en retard de 25 jours", tenant: "Youssef El Amrani", property: "Riad Dar El Badia", address: "Médina, Marrakech", due: "5 août 2026", amount: 6500, priority: "Critique", cta: "Relancer", image: "/properties/riad-medina.jpg", urgent: true },
  { id: "contract", kind: "contract", title: "Renouveler le contrat", subtitle: "Le contrat arrive à échéance dans 5 jours", tenant: "Fatima Zahra Bennani", property: "Résidence Les Orangers, Appt 8", address: "Hivernage, Marrakech", due: "4 sept. 2026", amount: 6000, priority: "Élevée", cta: "Renouveler", image: "/properties/appartement-gueliz.jpg", urgent: true },
  { id: "payment", kind: "payment", title: "Valider un paiement reçu", subtitle: "Virement reçu en attente de validation", tenant: "Karim Mouline", property: "Villa Anfa, RDC", address: "Targa, Marrakech", due: "Aujourd’hui", amount: 12000, priority: "Élevée", cta: "Valider", image: "/properties/villa-targa.jpg" },
  { id: "vacancy", kind: "vacancy", title: "Publier un bien vacant", subtitle: "Appartement prêt à la location", tenant: "Aucun locataire", property: "Appartement 23", address: "Guéliz, Marrakech", due: "Dans 2 jours", priority: "Moyenne", cta: "Publier", image: "/properties/appartement-gueliz.jpg" },
  { id: "document", kind: "document", title: "Compléter un document", subtitle: "Pièce d’identité manquante", tenant: "Nadia El Haddad", property: "Villa Anfa, étage", address: "Targa, Marrakech", due: "Dans 3 jours", priority: "Moyenne", cta: "Demander", image: "/properties/villa-targa.jpg" },
  { id: "inspection", kind: "inspection", title: "Vérifier l’état des lieux de sortie", subtitle: "Préparé par le locataire", tenant: "Mehdi Tahiri", property: "Résidence Les Orangers, Appt 5", address: "Hivernage, Marrakech", due: "Dans 7 jours", priority: "Faible", cta: "Consulter", image: "/properties/riad-medina.jpg" },
];
const icons = { late: FiAlertCircle, contract: FiClock, payment: FiCheck, vacancy: FiRadio, document: FiFileText, inspection: FiHome };
const money = (n: number) => `${n.toLocaleString("fr-FR")} DH`;

export default function DashboardPage() {
  const [biens, setBiens] = useState<Bien[]>([]), [loyers, setLoyers] = useState<Loyer[]>([]);
  const [selected, setSelected] = useState(actions[0]), [drawer, setDrawer] = useState(true), [toast, setToast] = useState<string | null>(null);
  useEffect(() => { Promise.all([getBiens(), getLoyers()]).then(([b, l]) => { setBiens(b); setLoyers(l); }).catch(() => undefined); }, []);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(null), 2600); return () => clearTimeout(id); }, [toast]);
  const totals = useMemo(() => { const paid = loyers.filter(l => l.statut === "paye").reduce((s, l) => s + l.montant, 0); const late = loyers.filter(l => l.statut === "retard").reduce((s, l) => s + l.montant, 0); const waiting = loyers.filter(l => l.statut === "en_attente").reduce((s, l) => s + l.montant, 0); return paid + late + waiting ? { paid, late, waiting, expected: paid + late + waiting } : { paid: 24500, late: 6500, waiting: 11500, expected: 42500 }; }, [loyers]);
  const rate = Math.round(totals.paid / totals.expected * 1000) / 10;
  const selectedBien = biens.find(b => b.nom === selected.property);
  const choose = (item: ActionItem) => { setSelected(item); setDrawer(true); };
  const act = (item: ActionItem) => { choose(item); setToast(`${item.cta} : action préparée pour ${item.tenant}.`); };

  return <div className="min-h-screen bg-[#fbfaf7] text-[#132238]">
    <header className="flex flex-col gap-4 border-b border-[#e7e5df] px-5 py-5 sm:px-8 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="font-syne text-3xl font-bold tracking-[-.04em] text-[#0f1d33] sm:text-4xl">À traiter aujourd’hui</h1><p className="mt-2 flex items-center gap-2 text-sm font-medium text-[#667085]"><FiCalendar /> Dimanche 30 août 2026</p></div><Link href="/biens" className="inline-flex w-fit items-center gap-2 rounded-lg bg-[#087b4c] px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-[#05643d]"><FiPlus /> Ajouter un bien</Link></header>
    <div className={`grid min-h-[calc(100vh-105px)] ${drawer ? "xl:grid-cols-[minmax(0,1fr)_300px]" : "grid-cols-1"}`}>
      <main className="min-w-0 px-4 py-5 sm:px-6 lg:px-8">
        <section className="overflow-hidden rounded-xl border border-[#e5e4df] bg-white">
          <SectionTitle color="#ef5546">Urgent (2)</SectionTitle><Labels />
          {actions.map((item, i) => <div key={item.id}>{i === 2 && <SectionTitle color="#f59e0b">Important (3)</SectionTitle>}{i === 5 && <SectionTitle color="#07965d">À suivre (1)</SectionTitle>}<ActionRow item={item} selected={selected.id === item.id} choose={choose} act={act} /></div>)}
        </section>
        <div className="mt-4 grid gap-4 lg:grid-cols-2"><Collection totals={totals} rate={rate} /><Expirations choose={choose} /></div>
      </main>
      {drawer && <aside className="relative border-l border-[#e5e4df] bg-white p-5 xl:sticky xl:top-0 xl:h-[calc(100vh-105px)] xl:overflow-y-auto"><button onClick={() => setDrawer(false)} className="absolute right-4 top-4 z-10 rounded-full bg-white/90 p-2 shadow" aria-label="Fermer"><FiX /></button><p className="mb-3 text-[10px] font-bold uppercase tracking-[.1em] text-[#e84f40]">Bien sélectionné</p><Image src={selected.image} alt={selected.property} width={600} height={375} className="aspect-[16/10] w-full rounded-lg object-cover" priority /><h2 className="mt-5 font-syne text-xl font-bold">{selected.property}</h2><p className="mt-1 text-sm text-[#667085]">{selected.address}</p><dl className="mt-5 divide-y divide-[#ebe8e3] border-y border-[#ebe8e3]"><Detail icon={<FiUser />} label="Locataire actuel" value={selected.tenant} sub="+212 6 11 22 33 44" /><Detail icon={<FiHome />} label="Loyer / mois" value={money(selectedBien?.loyer_base ?? selected.amount ?? 6500)} /><Detail icon={<FiAlertCircle />} label="Statut du paiement" value={selected.urgent ? "En retard" : "À jour"} sub={selected.due} danger={selected.urgent} /><Detail icon={<FiCalendar />} label="Fin de contrat" value="15 févr. 2027" sub="Dans 5 mois" /></dl><Link href={selectedBien ? `/biens/${selectedBien.id}` : "/biens"} className="mt-5 flex items-center justify-center gap-3 rounded-lg bg-[#087b4c] px-4 py-3.5 text-sm font-semibold text-white">Voir le bien <FiArrowRight /></Link></aside>}
    </div>
    {toast && <div role="status" className="fixed bottom-5 right-5 z-50 flex items-center gap-3 rounded-lg bg-[#10223a] px-4 py-3 text-sm font-medium text-white shadow-xl"><FiSend className="text-[#38d493]" />{toast}</div>}
  </div>;
}

function SectionTitle({ color, children }: { color: string; children: React.ReactNode }) { return <div className="flex items-center gap-2 border-b border-[#e9e7e2] bg-[#fcfbf8] px-4 py-3 text-sm font-semibold"><span className="h-2.5 w-2.5 rounded-full" style={{ background: color }} />{children}</div>; }
function Labels() { return <div className="hidden grid-cols-[2.2fr_1.2fr_.8fr_.65fr_.65fr] gap-4 border-b border-[#eeeae5] px-4 py-2 text-[10px] font-bold uppercase tracking-[.08em] text-[#8b92a0] md:grid"><span>Action</span><span>Contexte</span><span>Échéance</span><span>Priorité</span><span className="text-right">Action</span></div>; }
function ActionRow({ item, selected, choose, act }: { item: ActionItem; selected: boolean; choose: (i: ActionItem) => void; act: (i: ActionItem) => void }) { const Icon = icons[item.kind]; return <button onClick={() => choose(item)} className={`grid w-full gap-3 border-b border-[#efede9] px-4 py-3 text-left md:grid-cols-[2.2fr_1.2fr_.8fr_.65fr_.65fr] md:items-center md:gap-4 ${selected ? "bg-[#fff9f6] shadow-[inset_3px_0_0_#ef6a5b]" : "hover:bg-[#fbfaf7]"}`}><span className="flex min-w-0 items-center gap-3"><Image src={item.image} alt="" width={92} height={62} className="h-[62px] w-[92px] shrink-0 rounded-md object-cover" /><span><span className="flex items-start gap-2 font-semibold"><Icon className={`mt-0.5 shrink-0 ${item.urgent ? "text-[#ef5546]" : "text-[#078957]"}`} />{item.title}</span><span className="mt-1 block text-xs leading-5 text-[#697386]">{item.subtitle}</span></span></span><span><strong className="block text-sm">{item.tenant}</strong><span className="mt-1 block text-xs text-[#697386]">{item.property}</span></span><span className={`text-sm font-semibold ${item.urgent ? "text-[#e84f40]" : "text-[#344054]"}`}>{item.due}{item.amount && <small className="mt-1 block text-[#697386]">{money(item.amount)}{item.kind === "contract" ? "/mois" : ""}</small>}</span><span><em className={`not-italic rounded px-2 py-1 text-xs font-semibold ${item.priority === "Critique" ? "bg-[#fff0ed] text-[#d83a2f]" : item.priority === "Élevée" ? "bg-[#fff3e7] text-[#ce6813]" : "bg-[#eaf7ef] text-[#147447]"}`}>{item.priority}</em></span><span className="flex justify-end"><span onClick={e => { e.stopPropagation(); act(item); }} className={`inline-flex min-w-[86px] justify-center rounded-md border px-3 py-2 text-xs font-semibold ${item.urgent ? "border-[#ef786b] text-[#df4336]" : "border-[#148a5b] text-[#087749]"}`}>{item.cta}</span></span></button>; }
function Collection({ totals, rate }: { totals: { paid: number; late: number; waiting: number; expected: number }; rate: number }) { return <section className="rounded-xl border border-[#e5e4df] bg-white p-5"><div className="flex justify-between"><div><h2 className="font-semibold">Encaissements — août 2026</h2><p className="mt-4 text-2xl font-bold">{money(totals.paid)} <small className="text-sm font-medium text-[#667085]">encaissés</small></p><p className="text-xs text-[#7b8492]">sur {money(totals.expected)} attendus</p></div><strong className="text-2xl text-[#078957]">{rate}%</strong></div><div className="mt-4 h-2 rounded-full bg-[#edf0ee]"><div className="h-full rounded-full bg-[#0a8b58]" style={{ width: `${rate}%` }} /></div><div className="mt-5 grid grid-cols-3 divide-x text-xs"><Stat label="Encaissés" value={totals.paid} /><Stat label="En attente" value={totals.waiting} /><Stat label="En retard" value={totals.late} /></div><Link href="/loyers" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#087b4c]">Voir les paiements <FiArrowRight /></Link></section>; }
function Stat({ label, value }: { label: string; value: number }) { return <div className="px-3 first:pl-0"><span className="text-[#667085]">{label}</span><strong className="mt-1 block text-sm">{money(value)}</strong></div>; }
function Expirations({ choose }: { choose: (i: ActionItem) => void }) { return <section className="rounded-xl border border-[#e5e4df] bg-white p-5"><div className="flex justify-between"><h2 className="font-semibold">Contrats qui expirent bientôt</h2><Link href="/contrats" className="text-xs font-semibold text-[#087b4c]">Voir tous</Link></div><div className="mt-3 divide-y">{actions.filter(a => ["contract", "inspection"].includes(a.kind)).map(a => <button key={a.id} onClick={() => choose(a)} className="grid w-full grid-cols-[1fr_auto] gap-3 py-3 text-left"><span><strong className="block">{a.tenant}</strong><small className="text-[#697386]">{a.property}</small></span><span className="text-right"><strong>{a.due}</strong><small className="block text-[#ef5546]">Échéance proche</small></span></button>)}</div></section>; }
function Detail({ icon, label, value, sub, danger }: { icon: React.ReactNode; label: string; value: string; sub?: string; danger?: boolean }) { return <div className="flex gap-3 py-4"><span className="text-lg">{icon}</span><div><dt className="text-[10px] font-bold uppercase tracking-[.07em] text-[#7b8492]">{label}</dt><dd className={`mt-1 text-sm font-semibold ${danger ? "text-[#e84f40]" : ""}`}>{value}</dd>{sub && <small className="text-[#697386]">{sub}</small>}</div></div>; }
