import fs from 'node:fs/promises';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const W = 1280, H = 720;
const OUT = 'C:/A__MON PC/3_PROJETS DIGITAUX/3_EASY LOCATION_Immo/Competencia_IA_Soutenance.pptx';
const MEDIA = 'C:/A__MON PC/3_PROJETS DIGITAUX/3_EASY LOCATION_Immo/_ppt_build/media';
const C = { ink:'#101828', blue:'#123E9B', cyan:'#2BB3D6', pale:'#F4F7FB', line:'#D6DEE9', muted:'#667085', white:'#FFFFFF', green:'#12B76A', orange:'#F79009', red:'#E5484D', dark:'#0B1B4D' };

async function bytes(path){ const b=await fs.readFile(path); return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength); }
function box(slide, x,y,w,h, fill='none', line='none', radius=0){ return slide.shapes.add({geometry: radius?'roundRect':'rect', position:{left:x,top:y,width:w,height:h}, fill, line:{style:'solid',fill:line,width:line==='none'?0:1}, ...(radius?{borderRadius:'rounded-xl'}:{})}); }
function text(slide, s, x,y,w,h, style={}){ const sh=slide.shapes.add({geometry:'textbox', position:{left:x,top:y,width:w,height:h}, fill:'none', line:{style:'solid',fill:'none',width:0}}); sh.text=s; sh.text.style={fontFamily:'Arial',fontSize:style.size||20,color:style.color||C.ink,bold:!!style.bold,alignment:style.align||'left',verticalAlignment:style.valign||'top',italic:!!style.italic}; return sh; }
function rule(slide,x,y,w,color=C.line,width=2){ return slide.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:width},fill:color,line:{style:'solid',fill:color,width:0}}); }
async function image(slide,name,x,y,w,h,fit='contain'){ const p=`${MEDIA}/${name}`; slide.images.add({blob:await bytes(p),contentType:'image/png',alt:name,fit,position:{left:x,top:y,width:w,height:h}}); }
function footer(slide,n,section='COMPETENCIA IA'){ text(slide,section,72,682,350,18,{size:11,color:C.muted,bold:true}); text(slide,String(n).padStart(2,'0'),1180,682,28,18,{size:11,color:C.muted,align:'right'}); }
function title(slide,kicker,headline,sub=''){ text(slide,kicker.toUpperCase(),72,42,600,22,{size:13,color:C.blue,bold:true}); text(slide,headline,72,78,1120,70,{size:35,bold:true,color:C.ink}); if(sub) text(slide,sub,72,155,1050,44,{size:18,color:C.muted}); rule(slide,72,215,1136,C.line,1); }
function notes(slide, extra=''){ slide.speakerNotes.textFrame.setText(`[Sources]\nRapport fourni : 1A__Rapport Complet VF_10_07_2026.docx${extra?'\n'+extra:''}`); slide.speakerNotes.setVisible(true); }
function bullet(slide, s, x,y,w, color=C.ink, size=21){ text(slide,'•',x,y,22,28,{size,bold:true,color:C.cyan}); text(slide,s,x+30,y,w,34,{size,color}); }
function metric(slide, val, label, x,y,w,accent=C.blue){ text(slide,val,x,y,w,62,{size:46,bold:true,color:accent}); text(slide,label,x,y+65,w,40,{size:17,color:C.muted}); }

async function main(){
 const p = Presentation.create({slideSize:{width:W,height:H}});
 let n=0;
 function add(k,h,s=''){ const sl=p.slides.add(); sl.background.fill=C.white; title(sl,k,h,s); n++; footer(sl,n); notes(sl); return sl; }

 // 1 cover
 { const sl=p.slides.add(); sl.background.fill=C.dark; n++; box(sl,0,0,510,H,C.blue,'none'); await image(sl,'image1.png',88,100,210,210); text(sl,'SOUTENANCE',72,370,330,26,{size:16,color:'#A9D8FF',bold:true}); text(sl,'Competencia IA',72,408,520,72,{size:52,bold:true,color:C.white}); text(sl,'Plateforme d’intelligence artificielle générative pour l’ingénierie pédagogique des formateurs OFPPT',72,490,470,100,{size:22,color:'#DCE7FF'}); text(sl,'ElMustapha EZZOUHIR\nEncadré par : Mustapha LOUAFIR',72,625,460,50,{size:16,color:C.white}); text(sl,'Concours de promotion interne — Échelle 22',690,200,440,34,{size:18,color:C.blue,bold:true}); text(sl,'Préparer mieux.\nEn moins de deux minutes.',690,270,480,140,{size:40,bold:true,color:C.ink}); rule(sl,690,440,440,C.cyan,5); text(sl,'Une innovation pédagogique ancrée dans le référentiel OFPPT.',690,475,430,60,{size:22,color:C.muted}); text(sl,'2026',1090,650,90,30,{size:16,color:C.muted,align:'right'}); notes(sl,'Visuel : logo OFPPT extrait du rapport fourni.'); }

 let sl;
 sl=add('Le point de départ','Le formateur doit consacrer son énergie à la pédagogie','La production documentaire prend trop de place dans le quotidien.'); metric(sl,'1 à 3 h','pour préparer une séance conforme',92,270,260,C.red); metric(sl,'20–25 h','par mois pour 20 séances',455,270,300,C.orange); metric(sl,'< 2 min','avec Competencia IA',850,270,300,C.green); rule(sl,72,545,1136,C.line,1); text(sl,'Le projet ne remplace pas l’expertise du formateur : il la rend immédiatement exploitable.',92,575,1000,40,{size:24,bold:true,color:C.blue});
 sl=add('Contexte institutionnel','La transformation numérique crée une fenêtre d’action','Le projet s’inscrit dans la modernisation de la formation professionnelle au Maroc.'); bullet(sl,'Former des compétences adaptées aux besoins de l’économie',110,270,500); bullet(sl,'Équiper les établissements et accompagner les formateurs',110,335,500); bullet(sl,'Intégrer l’IA dans des pratiques pédagogiques concrètes',110,400,500); box(sl,735,260,350,210,C.pale,C.line,1); text(sl,'OFPPT',775,295,270,50,{size:34,bold:true,color:C.blue,align:'center'}); text(sl,'EFP  →  DR  →  DG',775,365,270,32,{size:24,bold:true,color:C.ink,align:'center'}); text(sl,'Une logique de proximité, de mutualisation et de pilotage.',770,420,280,50,{size:16,color:C.muted,align:'center'});
 sl=add('Le terrain','L’enquête confirme un problème de productivité et de capitalisation','47 formateurs ont nourri l’analyse de l’existant.'); metric(sl,'95 %','utilisent Word comme outil principal',100,270,270,C.blue); metric(sl,'< 20 %','disposent d’un modèle standardisé',500,270,300,C.orange); metric(sl,'85 %','sont intéressés par la génération automatique',900,270,300,C.green); text(sl,'Le problème n’est pas Word. C’est l’absence d’un environnement commun, structuré et réutilisable.',105,520,1060,60,{size:25,bold:true,color:C.ink,align:'center'});
 sl=add('Les dysfonctionnements','Cinq frictions transforment un travail utile en tâches répétitives','Elles touchent le temps, la qualité et la continuité pédagogique.'); const dys=[['Temps de production excessif','Fatigue, moins de temps d’animation',C.red],['Modèles hétérogènes','Qualité variable entre formateurs',C.orange],['Référentiel peu intégré','Compétences parfois mal couvertes',C.blue],['Ressources isolées','Perte de mémoire pédagogique',C.cyan],['Suivi peu traçable','Reporting long et fragile',C.green]]; dys.forEach((d,i)=>{let y=255+i*68; box(sl,90,y,16,42,d[2],'none'); text(sl,d[0],130,y,330,30,{size:21,bold:true}); text(sl,d[1],505,y,550,30,{size:19,color:C.muted}); rule(sl,90,y+49,1020,C.line,1);});
 sl=add('La problématique','Comment faire de l’IA un levier de productivité pédagogique ?','La réponse doit respecter la complexité des documents et l’exigence du référentiel.'); box(sl,120,280,1040,180,C.pale,C.line,1); text(sl,'Comment automatiser la génération de ressources pédagogiques,\ntout en garantissant leur alignement, leur partage et leur suivi ?',170,320,940,100,{size:32,bold:true,color:C.blue,align:'center'}); text(sl,'Trois exigences structurent la solution : produire juste, partager mieux, suivre dans la durée.',170,500,940,34,{size:20,color:C.muted,align:'center'});
 sl=add('Les objectifs','Une plateforme utile à la fois au formateur et à l’institution','Le projet poursuit deux niveaux d’impact complémentaires.'); box(sl,92,270,500,250,C.pale,C.line,1); text(sl,'Niveau opérationnel',125,300,400,35,{size:25,bold:true,color:C.blue}); bullet(sl,'Générer séances, fiches et évaluations',125,360,400); bullet(sl,'Partager et réutiliser les ressources',125,415,400); bullet(sl,'Suivre les compétences des stagiaires',125,470,400); box(sl,675,270,500,250,'#EAF8F2',C.line,1); text(sl,'Niveau institutionnel',708,300,400,35,{size:25,bold:true,color:C.green}); bullet(sl,'Visualiser l’activité pédagogique',708,360,400); bullet(sl,'Piloter EFP, DR et DG',708,415,400); bullet(sl,'Exporter des données structurées',708,470,400);
 sl=add('Le parti pris','L’IA génère, le formateur valide','La plateforme est conçue comme un assistant, pas comme un substitut.'); text(sl,'Référentiel',110,305,260,40,{size:25,bold:true,color:C.blue,align:'center'}); text(sl,'→',390,305,90,40,{size:35,bold:true,color:C.cyan,align:'center'}); text(sl,'Contexte pédagogique',480,305,300,40,{size:25,bold:true,color:C.blue,align:'center'}); text(sl,'→',810,305,90,40,{size:35,bold:true,color:C.cyan,align:'center'}); text(sl,'Génération IA',900,305,250,40,{size:25,bold:true,color:C.blue,align:'center'}); rule(sl,150,410,940,C.cyan,4); text(sl,'Le formateur relit, ajuste, régénère et exporte.',350,455,580,42,{size:27,bold:true,color:C.ink,align:'center'});
 sl=add('La méthode','Un développement par itérations, guidé par le besoin réel','Le choix du vibe coding a accéléré le passage de l’idée à l’usage.'); const steps=[['1','Décrire','Le besoin en langage naturel'],['2','Générer','Une première version avec l’IA'],['3','Tester','La fonctionnalité en situation'],['4','Ajuster','Jusqu’à obtenir le comportement attendu']]; steps.forEach((a,i)=>{let x=90+i*275; box(sl,x,300,220,145,C.pale,C.line,1); text(sl,a[0],x+20,320,55,55,{size:38,bold:true,color:C.cyan}); text(sl,a[1],x+85,322,120,30,{size:22,bold:true,color:C.blue}); text(sl,a[2],x+20,380,180,48,{size:17,color:C.muted}); if(i<3) text(sl,'→',x+225,350,40,40,{size:30,bold:true,color:C.cyan,align:'center'});}); text(sl,'Rôle du porteur : décrire, tester, juger, recommencer.',280,540,720,34,{size:24,bold:true,color:C.ink,align:'center'});
 sl=add('Les utilisateurs','Le formateur est le centre de gravité de la plateforme','Les autres profils bénéficient d’une vision adaptée à leur niveau d’action.'); text(sl,'FORMATEUR',120,275,240,30,{size:19,bold:true,color:C.blue,align:'center'}); text(sl,'STAGIAIRE',450,275,240,30,{size:19,bold:true,color:C.blue,align:'center'}); text(sl,'EFP / DR / DG',780,275,260,30,{size:19,bold:true,color:C.blue,align:'center'}); rule(sl,240,335,1,C.cyan,4); rule(sl,570,335,1,C.cyan,4); rule(sl,910,335,1,C.cyan,4); text(sl,'Produit\nGère\nSuit',155,365,170,105,{size:26,bold:true,color:C.ink,align:'center'}); text(sl,'Participe\naux simulations',480,365,170,105,{size:26,bold:true,color:C.ink,align:'center'}); text(sl,'Consulte\nPilote\nExporte',810,365,200,105,{size:26,bold:true,color:C.ink,align:'center'}); text(sl,'Un accès par rôle pour protéger les données et clarifier les usages.',240,550,800,34,{size:22,color:C.muted,align:'center'});
 sl=add('Le référentiel','Le référentiel OFPPT devient l’épine dorsale de la génération','Chaque production part d’une sélection pédagogique contextualisée.'); const hier=['Filière','Module','Séquence','Compétence','Objectif / critère']; hier.forEach((v,i)=>{let x=88+i*225; box(sl,x,305,190,88,i===4?'#EAF8F2':C.pale,C.line,1); text(sl,v,x+10,334,170,28,{size:20,bold:true,color:i===4?C.green:C.blue,align:'center'}); if(i<4) text(sl,'→',x+194,330,30,30,{size:25,bold:true,color:C.cyan,align:'center'});}); text(sl,'Résultat : une IA qui travaille à partir d’un contexte, et non à l’aveugle.',170,500,940,36,{size:24,bold:true,color:C.ink,align:'center'});
 sl=add('Conception fonctionnelle','Les cas d’utilisation couvrent toute la chaîne de valeur','La plateforme relie production, collaboration, suivi et pilotage.'); await image(sl,'image7.png',90,270,560,280); text(sl,'Actions communes',740,300,350,30,{size:23,bold:true,color:C.blue}); bullet(sl,'S’authentifier et gérer son profil',740,355,390); bullet(sl,'Consulter le tableau de bord',740,410,390); bullet(sl,'Accéder aux services selon son rôle',740,465,390);
 sl=add('Le modèle de données','Une structure conçue pour relier contenus, compétences et usages','Le modèle soutient à la fois la génération et le pilotage.'); const ents=[['Utilisateur','rôle, établissement'],['Référentiel','filière → compétence'],['Ressources','séance, fiche, évaluation'],['Suivi','groupe, stagiaire, acquisition'],['Collaboration','likes, commentaires, partage'],['Simulation','entreprise virtuelle, run']]; ents.forEach((e,i)=>{let x=100+(i%3)*360,y=270+Math.floor(i/3)*145; box(sl,x,y,300,105,C.pale,C.line,1); text(sl,e[0],x+20,y+20,260,28,{size:22,bold:true,color:C.blue}); text(sl,e[1],x+20,y+60,260,24,{size:17,color:C.muted});});
 sl=add('Architecture technique','Une stack moderne, adaptée à une application web SaaS','Les choix privilégient maturité, productivité et performances en production.'); const tech=[['Next.js / React','Interface et routes applicatives'],['TypeScript','Fiabilité et maintenabilité'],['Supabase / PostgreSQL','Données et authentification'],['Prisma ORM','Accès typé à la base'],['Claude API','Extraction et génération'],['Vercel','Hébergement et déploiement']]; tech.forEach((e,i)=>{let y=260+i*60; text(sl,e[0],110,y,270,28,{size:20,bold:true,color:C.blue}); text(sl,e[1],430,y,540,28,{size:19,color:C.muted}); rule(sl,110,y+38,860,C.line,1);}); box(sl,1000,275,170,230,C.dark,'none',1); text(sl,'IA\n+\nWeb\n+\nDonnées',1020,315,130,150,{size:27,bold:true,color:C.white,align:'center'});
 sl=add('Sécurité et continuité','Deux garde-fous protègent l’expérience utilisateur','La fluidité de l’IA ne doit pas fragiliser la confiance.'); box(sl,110,290,440,190,C.pale,C.line,1); text(sl,'Sécurité par rôle',150,325,360,34,{size:26,bold:true,color:C.blue,align:'center'}); text(sl,'Les utilisateurs accèdent uniquement\naux données de leur périmètre.',150,385,360,60,{size:21,color:C.muted,align:'center'}); box(sl,690,290,440,190,'#EAF8F2',C.line,1); text(sl,'Fallback automatique',730,325,360,34,{size:26,bold:true,color:C.green,align:'center'}); text(sl,'Si le service principal est indisponible,\nla génération bascule vers un second modèle.',730,385,360,60,{size:21,color:C.muted,align:'center'});
 sl=add('Expérience centrale','Une séance complète se construit en moins de deux minutes','Le parcours réduit la saisie et laisse le contrôle au formateur.'); await image(sl,'image10.png',90,255,710,365); text(sl,'1. Sélectionner le contexte',850,300,310,32,{size:22,bold:true,color:C.blue}); text(sl,'2. Générer en streaming',850,360,310,32,{size:22,bold:true,color:C.blue}); text(sl,'3. Modifier et exporter',850,420,310,32,{size:22,bold:true,color:C.blue}); text(sl,'PDF · Word · PowerPoint',850,500,310,34,{size:24,bold:true,color:C.green});
 sl=add('Séances pédagogiques','Le streaming transforme l’attente en interaction','Le contenu apparaît ligne par ligne, pour permettre un contrôle immédiat.'); await image(sl,'image10.png',90,260,700,360); bullet(sl,'Sélection cascade : filière → module → séquence → compétence',850,300,340, C.ink,18); bullet(sl,'Instructions spécifiques optionnelles',850,370,340,C.ink,18); bullet(sl,'Régénérer, modifier ou exporter',850,440,340,C.ink,18);
 sl=add('Fiches pédagogiques','La même logique produit des documents homogènes','La cohérence d’interface accélère la prise en main.'); await image(sl,'image11.png',90,260,700,360); text(sl,'Paramètres pédagogiques',850,305,320,30,{size:22,bold:true,color:C.blue}); text(sl,'Objectifs · durée · méthodes\nconsignes particulières',850,355,330,65,{size:20,color:C.muted}); text(sl,'Un même geste, plusieurs types de ressources.',850,475,330,50,{size:22,bold:true,color:C.green});
 sl=add('Évaluations','Générer des évaluations adaptées au niveau visé','Le formateur choisit la forme, la difficulté et le volume.'); await image(sl,'image12.png',90,260,700,360); text(sl,'Paramètres configurables',850,305,320,30,{size:22,bold:true,color:C.blue}); bullet(sl,'Type et niveau de difficulté',850,360,330,C.ink,18); bullet(sl,'Nombre de questions',850,415,330,C.ink,18); bullet(sl,'Objectifs pédagogiques',850,470,330,C.ink,18);
 sl=add('Bibliothèque collaborative','La ressource produite une fois peut servir à plusieurs','La capitalisation devient un réflexe collectif.'); await image(sl,'image15.png',90,260,700,360); text(sl,'Rechercher',850,300,300,28,{size:21,bold:true,color:C.blue}); text(sl,'par type, filière, module ou mot-clé',850,335,330,28,{size:18,color:C.muted}); text(sl,'Partager',850,410,300,28,{size:21,bold:true,color:C.blue}); text(sl,'likes, commentaires, copie dans l’espace de travail',850,445,330,50,{size:18,color:C.muted});
 sl=add('Assistant IA','Un accompagnement conversationnel disponible au fil du travail','Le formateur peut demander, reformuler, approfondir et réutiliser.'); await image(sl,'image16.png',90,255,710,370); text(sl,'Préparer une activité',850,300,330,30,{size:22,bold:true,color:C.blue}); text(sl,'Reformuler un objectif\nCréer un exercice\nProposer une méthode',850,355,320,110,{size:20,color:C.muted}); text(sl,'La conversation devient un espace de préparation.',850,520,330,44,{size:22,bold:true,color:C.green});
 sl=add('Competencia Simulator','Apprendre en prenant des décisions','L’entreprise virtuelle rapproche les stagiaires des situations professionnelles.'); await image(sl,'image13.png',90,260,700,360); text(sl,'Une entreprise marocaine fictive',850,305,330,32,{size:22,bold:true,color:C.blue}); text(sl,'secteur · équipe · clients · fournisseurs\ncontraintes et scénarios de décision',850,360,330,70,{size:19,color:C.muted}); text(sl,'≈ 70–90 s pour générer le contexte',850,485,330,30,{size:19,bold:true,color:C.orange});
 sl=add('Le déroulé d’une simulation','Six étapes font passer de la configuration au feedback','Chaque décision modifie les indicateurs de l’entreprise.'); const sim=['Ouvrir','Contextualiser','Générer','Lancer','Décider','Évaluer']; sim.forEach((v,i)=>{let x=78+i*188; text(sl,String(i+1),x,285,55,55,{size:38,bold:true,color:C.cyan}); text(sl,v,x,350,140,30,{size:20,bold:true,color:C.blue}); if(i<5) text(sl,'→',x+145,290,35,35,{size:24,bold:true,color:C.cyan,align:'center'});}); rule(sl,110,440,1000,C.cyan,4); text(sl,'Satisfaction client · santé financière · moral d’équipe · score global',150,500,980,35,{size:24,bold:true,color:C.ink,align:'center'});
 sl=add('Le rapport IA','La simulation se termine par une évaluation exploitable','Le feedback transforme l’expérience en apprentissage.'); await image(sl,'image14.png',90,255,710,370); text(sl,'Le rapport couvre :',850,300,320,30,{size:22,bold:true,color:C.blue}); bullet(sl,'note sur 20 et score pédagogique',850,355,340,C.ink,18); bullet(sl,'compétences mobilisées',850,410,340,C.ink,18); bullet(sl,'forces, erreurs et conseils personnalisés',850,465,340,C.ink,18);
 sl=add('Tableau de bord','Une vue synthétique relie production et progression','Le formateur voit ce qui mérite son attention aujourd’hui.'); await image(sl,'image9.png',90,255,730,370); text(sl,'Activité récente',865,300,300,30,{size:22,bold:true,color:C.blue}); text(sl,'Statistiques de production\nRessources les plus appréciées\nTaux de complétion des groupes',865,355,310,110,{size:20,color:C.muted});
 sl=add('La valeur créée','Le gain ne se limite pas à la vitesse','Competencia IA agit sur quatre dimensions de la pratique pédagogique.'); const vals=[['Temps','Préparer plus vite',C.red],['Qualité','Structurer avec le référentiel',C.blue],['Capitalisation','Réutiliser l’expertise',C.cyan],['Pilotage','Décider avec des données',C.green]]; vals.forEach((v,i)=>{let x=100+i*275; box(sl,x,290,220,170,C.pale,C.line,1); text(sl,v[0],x+20,320,180,30,{size:24,bold:true,color:v[2],align:'center'}); text(sl,v[1],x+20,380,180,50,{size:20,color:C.ink,align:'center'});}); text(sl,'Le formateur récupère du temps pour ce qui ne peut pas être automatisé : la relation pédagogique.',140,535,1000,55,{size:25,bold:true,color:C.ink,align:'center'});
 sl=add('Résultats et retours','Le prototype est fonctionnel et déployé','Les premiers retours confirment l’intérêt d’un assistant pédagogique contextualisé.'); metric(sl,'Fonctionnelle','plateforme web déployée',130,285,260,C.green); metric(sl,'Multi-format','PDF · Word · PowerPoint',510,285,280,C.blue); metric(sl,'Multi-module','production · partage · suivi · simulation',860,285,300,C.cyan); box(sl,190,510,900,70,'#EAF8F2',C.line,1); text(sl,'« Un assistant pédagogique disponible à minuit, qui connaît le référentiel OFPPT. »',220,528,840,30,{size:21,italic:true,color:C.green,align:'center'});
 sl=add('Limites à garder en tête','L’IA accélère la production, elle ne garantit pas seule la pertinence','La validation humaine reste une étape pédagogique indispensable.'); bullet(sl,'Les contenus doivent être relus et adaptés au groupe',120,290,900); bullet(sl,'La qualité dépend du contexte fourni et du référentiel disponible',120,360,900); bullet(sl,'Les usages institutionnels exigent accompagnement et gouvernance',120,430,900); text(sl,'La bonne question n’est pas « l’IA peut-elle produire ? » mais « comment l’intégrer avec discernement ? »',150,550,980,50,{size:24,bold:true,color:C.blue,align:'center'});
 sl=add('Feuille de route','La prochaine étape est l’automatisation pédagogique','Competencia doit passer de la génération ponctuelle à la planification continue.'); const road=[['Court terme','Notifications et recommandations'],['Moyen terme','Simulation jouée directement par le stagiaire'],['Long terme','Connexion au SI OFPPT et analyse d’alignement']]; road.forEach((r,i)=>{let y=285+i*95; text(sl,r[0].toUpperCase(),120,y,210,28,{size:16,bold:true,color:C.blue}); rule(sl,350,y+12,50,C.cyan,4); text(sl,r[1],440,y,650,32,{size:24,bold:true,color:C.ink});});
 sl=add('Perspectives fonctionnelles','Trois extensions peuvent amplifier l’impact','La feuille de route s’appuie sur les besoins déjà observés.'); const pers=[['Planification','Programme annuel, rappels, remédiation'],['Mobilité','Application native, hors ligne, dictée vocale'],['IA avancée','Personnalisation, correction et dialogue naturel']]; pers.forEach((r,i)=>{let x=100+i*360; box(sl,x,290,300,190,C.pale,C.line,1); text(sl,r[0],x+20,325,260,35,{size:25,bold:true,color:C.blue,align:'center'}); text(sl,r[1],x+25,390,250,55,{size:19,color:C.muted,align:'center'});});
 sl=add('Perspectives institutionnelles','L’outil individuel peut devenir un instrument de pilotage','La donnée pédagogique gagne en visibilité sans perdre sa finalité terrain.'); text(sl,'Formateur',140,300,220,35,{size:24,bold:true,color:C.blue,align:'center'}); text(sl,'→',380,300,80,35,{size:30,bold:true,color:C.cyan,align:'center'}); text(sl,'EFP',470,300,170,35,{size:24,bold:true,color:C.blue,align:'center'}); text(sl,'→',660,300,80,35,{size:30,bold:true,color:C.cyan,align:'center'}); text(sl,'DR',750,300,170,35,{size:24,bold:true,color:C.blue,align:'center'}); text(sl,'→',940,300,80,35,{size:30,bold:true,color:C.cyan,align:'center'}); text(sl,'DG',1030,300,150,35,{size:24,bold:true,color:C.blue,align:'center'}); rule(sl,160,410,960,C.cyan,4); text(sl,'Une chaîne de pilotage fondée sur l’activité réelle et les compétences acquises.',180,470,920,42,{size:25,bold:true,color:C.ink,align:'center'});
 sl=add('Conclusion','Competencia IA remet la technologie à sa juste place','Elle libère du temps documentaire pour renforcer la relation pédagogique.'); text(sl,'Un problème vécu sur le terrain',100,280,280,70,{size:25,bold:true,color:C.blue,align:'center'}); text(sl,'→',420,300,80,40,{size:32,bold:true,color:C.cyan,align:'center'}); text(sl,'Une plateforme contextualisée',500,280,280,70,{size:25,bold:true,color:C.blue,align:'center'}); text(sl,'→',820,300,80,40,{size:32,bold:true,color:C.cyan,align:'center'}); text(sl,'Un impact pédagogique',900,280,280,70,{size:25,bold:true,color:C.green,align:'center'}); rule(sl,160,430,960,C.cyan,5); text(sl,'L’innovation utile est celle qui s’intègre au quotidien de ceux qu’elle accompagne.',150,500,980,55,{size:29,bold:true,color:C.ink,align:'center'});
 sl=add('Ouverture','Merci pour votre attention','Questions et échanges'); text(sl,'Competencia IA',120,300,500,64,{size:48,bold:true,color:C.blue}); text(sl,'Transformer la préparation pédagogique\nen temps gagné pour apprendre mieux.',120,390,560,90,{size:28,color:C.ink}); await image(sl,'image1.png',900,245,190,190); text(sl,'competencia.one',120,585,300,30,{size:18,color:C.muted});

 await fs.writeFile('C:/A__MON PC/3_PROJETS DIGITAUX/3_EASY LOCATION_Immo/_ppt_build/source-notes.txt','Source principale : 1A__Rapport Complet VF_10_07_2026.docx, rapport fourni par l’utilisateur. Captures d’interface et logo OFPPT extraits du document source.');
 const pptx = await PresentationFile.exportPptx(p); await pptx.save(OUT);
 for (const [i,s] of p.slides.items.entries()){ const b=await p.export({slide:s,format:'png',scale:1}); await fs.writeFile(`C:/A__MON PC/3_PROJETS DIGITAUX/3_EASY LOCATION_Immo/_ppt_build/slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await b.arrayBuffer())); }
 const montage=await p.export({format:'webp',montage:true,scale:1}); await fs.writeFile('C:/A__MON PC/3_PROJETS DIGITAUX/3_EASY LOCATION_Immo/_ppt_build/montage.webp',new Uint8Array(await montage.arrayBuffer()));
 console.log(`Created ${n} slides at ${OUT}`);
}
main().catch(e=>{ console.error(e); process.exitCode=1; });
